--------------------------------------------------------
--  파일이 생성됨 - 토요일-1월-28-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ATCH_FILE_DETAIL
--------------------------------------------------------

  CREATE TABLE "ATCH_FILE_DETAIL" 
   (	"ATCH_FILE_ID" NUMBER, 
	"FILE_SN" NUMBER(3,0), 
	"FILE_STRE_COURS" VARCHAR2(2000 BYTE), 
	"STRE_FILE_NM" VARCHAR2(255 BYTE), 
	"ORIGNL_FILE_NM" VARCHAR2(255 BYTE), 
	"FILE_EXTSN" VARCHAR2(20 BYTE), 
	"FILE_CN" CLOB, 
	"FILE_SIZE" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("FILE_CN") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "ATCH_FILE_DETAIL"."ATCH_FILE_ID" IS '첨부파일ID';
   COMMENT ON COLUMN "ATCH_FILE_DETAIL"."FILE_SN" IS '파일순번';
   COMMENT ON COLUMN "ATCH_FILE_DETAIL"."FILE_STRE_COURS" IS '파일저장경로';
   COMMENT ON COLUMN "ATCH_FILE_DETAIL"."STRE_FILE_NM" IS '저장파일명';
   COMMENT ON COLUMN "ATCH_FILE_DETAIL"."ORIGNL_FILE_NM" IS '원본파일명';
   COMMENT ON COLUMN "ATCH_FILE_DETAIL"."FILE_EXTSN" IS '파일확장자';
   COMMENT ON COLUMN "ATCH_FILE_DETAIL"."FILE_CN" IS '파일내용';
   COMMENT ON COLUMN "ATCH_FILE_DETAIL"."FILE_SIZE" IS '파일크기';
REM INSERTING into ATCH_FILE_DETAIL
SET DEFINE OFF;
Insert into ATCH_FILE_DETAIL (ATCH_FILE_ID,FILE_SN,FILE_STRE_COURS,STRE_FILE_NM,ORIGNL_FILE_NM,FILE_EXTSN,FILE_SIZE) values (38,1,'d:/D_Other/upload_files\72c3b1348b3940e3917dfa81dcf95365','72c3b1348b3940e3917dfa81dcf95365','8월 출석부.pdf','pdf',138376);
Insert into ATCH_FILE_DETAIL (ATCH_FILE_ID,FILE_SN,FILE_STRE_COURS,STRE_FILE_NM,ORIGNL_FILE_NM,FILE_EXTSN,FILE_SIZE) values (38,2,'d:/D_Other/upload_files\eb32f4bc715f42efafe2d4e9d4b8f45f','eb32f4bc715f42efafe2d4e9d4b8f45f','9월 출석부.pdf','pdf',293642);
Insert into ATCH_FILE_DETAIL (ATCH_FILE_ID,FILE_SN,FILE_STRE_COURS,STRE_FILE_NM,ORIGNL_FILE_NM,FILE_EXTSN,FILE_SIZE) values (38,3,'d:/D_Other/upload_files\731ad70ce0364fb9b3077a26357e80b3','731ad70ce0364fb9b3077a26357e80b3','10월 출석부.pdf','pdf',279687);
Insert into ATCH_FILE_DETAIL (ATCH_FILE_ID,FILE_SN,FILE_STRE_COURS,STRE_FILE_NM,ORIGNL_FILE_NM,FILE_EXTSN,FILE_SIZE) values (39,1,'d:/D_Other/upload_files\91e89746f64c47a097454349af68f5e8','91e89746f64c47a097454349af68f5e8','10월 출석부.pdf','pdf',279687);
Insert into ATCH_FILE_DETAIL (ATCH_FILE_ID,FILE_SN,FILE_STRE_COURS,STRE_FILE_NM,ORIGNL_FILE_NM,FILE_EXTSN,FILE_SIZE) values (36,1,'d:/D_Other/upload_files\1bbe3be9587e4b889c8c46a86fc4de0d','1bbe3be9587e4b889c8c46a86fc4de0d','8월 출석부.pdf','pdf',138376);
Insert into ATCH_FILE_DETAIL (ATCH_FILE_ID,FILE_SN,FILE_STRE_COURS,STRE_FILE_NM,ORIGNL_FILE_NM,FILE_EXTSN,FILE_SIZE) values (37,1,'d:/D_Other/upload_files\6fde1b7fbdf24bb7a11fa20dc3288034','6fde1b7fbdf24bb7a11fa20dc3288034','8월 출석부.pdf','pdf',138376);
--------------------------------------------------------
--  DDL for Index ATCH_FILE_DETAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATCH_FILE_DETAIL_PK" ON "ATCH_FILE_DETAIL" ("ATCH_FILE_ID", "FILE_SN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ATCH_FILE_DETAIL
--------------------------------------------------------

  ALTER TABLE "ATCH_FILE_DETAIL" ADD CONSTRAINT "ATCH_FILE_DETAIL_PK" PRIMARY KEY ("ATCH_FILE_ID", "FILE_SN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ATCH_FILE_DETAIL" MODIFY ("FILE_EXTSN" NOT NULL ENABLE);
  ALTER TABLE "ATCH_FILE_DETAIL" MODIFY ("STRE_FILE_NM" NOT NULL ENABLE);
  ALTER TABLE "ATCH_FILE_DETAIL" MODIFY ("FILE_STRE_COURS" NOT NULL ENABLE);
  ALTER TABLE "ATCH_FILE_DETAIL" MODIFY ("FILE_SN" NOT NULL ENABLE);
  ALTER TABLE "ATCH_FILE_DETAIL" MODIFY ("ATCH_FILE_ID" NOT NULL ENABLE);
