--------------------------------------------------------
--  파일이 생성됨 - 토요일-1월-28-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ATCH_FILE
--------------------------------------------------------

  CREATE TABLE "ATCH_FILE" 
   (	"ATCH_FILE_ID" NUMBER, 
	"CREAT_DT" DATE DEFAULT SYSDATE, 
	"USE_AT" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ATCH_FILE"."ATCH_FILE_ID" IS '첨부파일ID';
   COMMENT ON COLUMN "ATCH_FILE"."CREAT_DT" IS '생성일시';
   COMMENT ON COLUMN "ATCH_FILE"."USE_AT" IS '사용여부';
REM INSERTING into ATCH_FILE
SET DEFINE OFF;
Insert into ATCH_FILE (ATCH_FILE_ID,CREAT_DT,USE_AT) values (21,to_date('2022/11/02','YYYY/MM/DD'),'Y');
Insert into ATCH_FILE (ATCH_FILE_ID,CREAT_DT,USE_AT) values (22,to_date('2022/11/02','YYYY/MM/DD'),'Y');
Insert into ATCH_FILE (ATCH_FILE_ID,CREAT_DT,USE_AT) values (23,to_date('2022/11/02','YYYY/MM/DD'),'Y');
Insert into ATCH_FILE (ATCH_FILE_ID,CREAT_DT,USE_AT) values (24,to_date('2022/11/02','YYYY/MM/DD'),'Y');
Insert into ATCH_FILE (ATCH_FILE_ID,CREAT_DT,USE_AT) values (25,to_date('2022/11/02','YYYY/MM/DD'),'Y');
Insert into ATCH_FILE (ATCH_FILE_ID,CREAT_DT,USE_AT) values (26,to_date('2022/11/02','YYYY/MM/DD'),'Y');
Insert into ATCH_FILE (ATCH_FILE_ID,CREAT_DT,USE_AT) values (27,to_date('2022/11/02','YYYY/MM/DD'),'Y');
Insert into ATCH_FILE (ATCH_FILE_ID,CREAT_DT,USE_AT) values (28,to_date('2022/11/02','YYYY/MM/DD'),'Y');
Insert into ATCH_FILE (ATCH_FILE_ID,CREAT_DT,USE_AT) values (29,to_date('2022/11/02','YYYY/MM/DD'),'Y');
Insert into ATCH_FILE (ATCH_FILE_ID,CREAT_DT,USE_AT) values (30,to_date('2022/11/02','YYYY/MM/DD'),'Y');
Insert into ATCH_FILE (ATCH_FILE_ID,CREAT_DT,USE_AT) values (31,to_date('2022/11/02','YYYY/MM/DD'),'Y');
Insert into ATCH_FILE (ATCH_FILE_ID,CREAT_DT,USE_AT) values (32,to_date('2022/11/02','YYYY/MM/DD'),'Y');
Insert into ATCH_FILE (ATCH_FILE_ID,CREAT_DT,USE_AT) values (33,to_date('2022/11/02','YYYY/MM/DD'),'Y');
Insert into ATCH_FILE (ATCH_FILE_ID,CREAT_DT,USE_AT) values (34,to_date('2022/11/02','YYYY/MM/DD'),'Y');
Insert into ATCH_FILE (ATCH_FILE_ID,CREAT_DT,USE_AT) values (35,to_date('2022/11/03','YYYY/MM/DD'),'Y');
Insert into ATCH_FILE (ATCH_FILE_ID,CREAT_DT,USE_AT) values (36,to_date('2022/11/03','YYYY/MM/DD'),'Y');
Insert into ATCH_FILE (ATCH_FILE_ID,CREAT_DT,USE_AT) values (37,to_date('2022/11/03','YYYY/MM/DD'),'Y');
Insert into ATCH_FILE (ATCH_FILE_ID,CREAT_DT,USE_AT) values (38,to_date('2022/11/03','YYYY/MM/DD'),'Y');
Insert into ATCH_FILE (ATCH_FILE_ID,CREAT_DT,USE_AT) values (39,to_date('2022/11/03','YYYY/MM/DD'),'Y');
--------------------------------------------------------
--  DDL for Index ATCH_FILE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATCH_FILE_PK" ON "ATCH_FILE" ("ATCH_FILE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ATCH_FILE
--------------------------------------------------------

  ALTER TABLE "ATCH_FILE" ADD CONSTRAINT "ATCH_FILE_PK" PRIMARY KEY ("ATCH_FILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ATCH_FILE" MODIFY ("CREAT_DT" NOT NULL ENABLE);
  ALTER TABLE "ATCH_FILE" MODIFY ("ATCH_FILE_ID" NOT NULL ENABLE);
