--------------------------------------------------------
--  파일이 생성됨 - 토요일-1월-28-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ATTACH
--------------------------------------------------------

  CREATE TABLE "ATTACH" 
   (	"ATT_NO" NUMBER(4,0), 
	"BO_NO" NUMBER(6,0), 
	"ATT_FILENAME" VARCHAR2(150 BYTE), 
	"ATT_SAVENAME" VARCHAR2(70 BYTE), 
	"ATT_MIME" VARCHAR2(100 BYTE), 
	"ATT_FILESIZE" NUMBER(10,0), 
	"ATT_FANCYSIZE" VARCHAR2(10 BYTE), 
	"ATT_DOWNLOAD" NUMBER(4,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ATTACH"."ATT_NO" IS '파일번호';
   COMMENT ON COLUMN "ATTACH"."BO_NO" IS '글번호';
   COMMENT ON COLUMN "ATTACH"."ATT_FILENAME" IS '파일명';
   COMMENT ON COLUMN "ATTACH"."ATT_SAVENAME" IS '저장명';
   COMMENT ON COLUMN "ATTACH"."ATT_MIME" IS '파일MIME';
   COMMENT ON COLUMN "ATTACH"."ATT_FILESIZE" IS '파일크기';
   COMMENT ON COLUMN "ATTACH"."ATT_FANCYSIZE" IS '팬시크기';
   COMMENT ON COLUMN "ATTACH"."ATT_DOWNLOAD" IS '다운로드수';
REM INSERTING into ATTACH
SET DEFINE OFF;
Insert into ATTACH (ATT_NO,BO_NO,ATT_FILENAME,ATT_SAVENAME,ATT_MIME,ATT_FILESIZE,ATT_FANCYSIZE,ATT_DOWNLOAD) values (6,496,'9.jpg','4b26083f-bcd0-4821-84e5-a38e3860cb6f','image/jpeg',419596,'409 KB',0);
Insert into ATTACH (ATT_NO,BO_NO,ATT_FILENAME,ATT_SAVENAME,ATT_MIME,ATT_FILESIZE,ATT_FANCYSIZE,ATT_DOWNLOAD) values (5,495,'100101010.jpg','87a23ba0-ac86-45ec-8a14-f7723ec56eae','image/jpeg',57699,'56 KB',0);
--------------------------------------------------------
--  DDL for Index PK_ATTATCH
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ATTATCH" ON "ATTACH" ("ATT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ATTACH
--------------------------------------------------------

  ALTER TABLE "ATTACH" ADD CONSTRAINT "PK_ATTATCH" PRIMARY KEY ("ATT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ATTACH" MODIFY ("ATT_FANCYSIZE" NOT NULL ENABLE);
  ALTER TABLE "ATTACH" MODIFY ("ATT_FILESIZE" NOT NULL ENABLE);
  ALTER TABLE "ATTACH" MODIFY ("ATT_SAVENAME" NOT NULL ENABLE);
  ALTER TABLE "ATTACH" MODIFY ("ATT_FILENAME" NOT NULL ENABLE);
