--------------------------------------------------------
--  파일이 생성됨 - 토요일-1월-28-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FREEREPLY
--------------------------------------------------------

  CREATE TABLE "FREEREPLY" 
   (	"REP_NO" NUMBER(4,0), 
	"BO_NO" NUMBER(6,0), 
	"REP_CONTENT" VARCHAR2(200 CHAR), 
	"REP_WRITER" VARCHAR2(20 CHAR), 
	"REP_MAIL" VARCHAR2(50 CHAR), 
	"REP_PASS" VARCHAR2(200 BYTE), 
	"REP_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "FREEREPLY"."REP_NO" IS '덧글번호';
   COMMENT ON COLUMN "FREEREPLY"."BO_NO" IS '글번호';
   COMMENT ON COLUMN "FREEREPLY"."REP_CONTENT" IS '내용';
   COMMENT ON COLUMN "FREEREPLY"."REP_WRITER" IS '작성자';
   COMMENT ON COLUMN "FREEREPLY"."REP_MAIL" IS '이메일';
   COMMENT ON COLUMN "FREEREPLY"."REP_PASS" IS '비밀번호';
   COMMENT ON COLUMN "FREEREPLY"."REP_DATE" IS '작성일';
REM INSERTING into FREEREPLY
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_FREEREPLY
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_FREEREPLY" ON "FREEREPLY" ("REP_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FREEREPLY
--------------------------------------------------------

  ALTER TABLE "FREEREPLY" ADD CONSTRAINT "PK_FREEREPLY" PRIMARY KEY ("REP_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FREEREPLY" MODIFY ("REP_PASS" NOT NULL ENABLE);
  ALTER TABLE "FREEREPLY" MODIFY ("REP_WRITER" NOT NULL ENABLE);
  ALTER TABLE "FREEREPLY" MODIFY ("BO_NO" NOT NULL ENABLE);
