--------------------------------------------------------
--  파일이 생성됨 - 토요일-1월-28-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table JDBC_BOARD
--------------------------------------------------------

  CREATE TABLE "JDBC_BOARD" 
   (	"BOARD_NO" NUMBER, 
	"BOARD_TITLE" VARCHAR2(100 BYTE), 
	"BOARD_WRITER" VARCHAR2(50 BYTE), 
	"BOARD_DATE" DATE, 
	"BOARD_CONTENT" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("BOARD_CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into JDBC_BOARD
SET DEFINE OFF;
Insert into JDBC_BOARD (BOARD_NO,BOARD_TITLE,BOARD_WRITER,BOARD_DATE) values (21,'7','7',to_date('2022/10/17','YYYY/MM/DD'));
Insert into JDBC_BOARD (BOARD_NO,BOARD_TITLE,BOARD_WRITER,BOARD_DATE) values (23,'5','5',to_date('2022/10/17','YYYY/MM/DD'));
Insert into JDBC_BOARD (BOARD_NO,BOARD_TITLE,BOARD_WRITER,BOARD_DATE) values (22,'1','1',to_date('2022/10/17','YYYY/MM/DD'));
Insert into JDBC_BOARD (BOARD_NO,BOARD_TITLE,BOARD_WRITER,BOARD_DATE) values (24,'8','8',to_date('2022/10/17','YYYY/MM/DD'));
--------------------------------------------------------
--  DDL for Index PK_JDBC_BOARD
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_JDBC_BOARD" ON "JDBC_BOARD" ("BOARD_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table JDBC_BOARD
--------------------------------------------------------

  ALTER TABLE "JDBC_BOARD" ADD CONSTRAINT "PK_JDBC_BOARD" PRIMARY KEY ("BOARD_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JDBC_BOARD" MODIFY ("BOARD_DATE" NOT NULL ENABLE);
  ALTER TABLE "JDBC_BOARD" MODIFY ("BOARD_WRITER" NOT NULL ENABLE);
  ALTER TABLE "JDBC_BOARD" MODIFY ("BOARD_TITLE" NOT NULL ENABLE);
  ALTER TABLE "JDBC_BOARD" MODIFY ("BOARD_NO" NOT NULL ENABLE);
