SELECT B.*
FROM ( 
    SELECT ROWNUM RNUM, A.*
    FROM (
        SELECT MEM_ID, MEM_NAME -- ROWNUM은 의사코드(논리)임
        FROM MEMBER
        ORDER BY ROWID DESC
    ) A -- A는 INLINE VIEW
    --WHERE ROWNUM >= 11 AND ROWNUM <= 20; -- SELECT보다 WHERE가 먼저 실행되는데 ROWNUM은 조회하는 동안 만들어지는 거라 안 나옴
) B
WHERE RNUM >= 11 AND RNUM <= 20;

------------------------------------------------------------------------------------------------------------------------
SELECT PROD_ID, PROD_LGU, PROD_NAME, BUYER_NAME, PROD_PRICE, PROD_SALE,
    (SELECT COUNT(CART_PROD)
    FROM CART
    WHERE CART_PROD = 'P101000001') COUNT
FROM PRODVIEW

SELECT B.*
FROM (
    SELECT A.*, ROWNUM RNUM
    FROM (
        WITH CARTVIEW AS (
            SELECT CART_PROD, SUM(CART_QTY) CNT
            FROM CART INNER JOIN PROD ON (CART_PROD = PROD_ID)
            GROUP BY CART_PROD
            ORDER BY 1 ASC
        )
        SELECT PROD_ID, PROD_LGU, LPROD_NM, PROD_NAME, BUYER_NAME, PROD_PRICE, PROD_SALE, CNT
        FROM   PRODVIEW LEFT OUTER JOIN CARTVIEW ON (PROD_ID = CART_PROD)
        ORDER BY 1 ASC
    ) A
) B
WHERE RNUM >= #{startRow} AND RNUM <= #{endRow}



WITH CARTVIEW AS (
    SELECT CART_PROD, SUM(CART_QTY) CNT, COUNT(DISTINCT CART_PROD) CARTCOUNT
    FROM CART INNER JOIN PROD ON (CART_PROD = PROD_ID)
         INNER JOIN MEMBER ON (CART_MEMBER = MEM_ID)
    GROUP BY CART_PROD
    ORDER BY 1 ASC
)
SELECT PROD_ID, LPROD_NM, PROD_NAME, BUYER_NAME, PROD_PRICE, PROD_SALE, CNT, CARTCOUNT
FROM   PRODVIEW LEFT OUTER JOIN CARTVIEW ON (PROD_ID = CART_PROD)
ORDER BY 1 ASC

