INSERT ALL
INTO LPROD(LPROD_ID, LPROD_GU, LPROD_NM)
    VALUES (12, 'P601', '신규카테1')
INTO LPROD(LPROD_ID, LPROD_GU, LPROD_NM)
    VALUES (13, 'P602', '신규카테2')
SELECT * FROM DUAL;

SELECT ', ' || COLUMN_NAME
FROM COLS
WHERE TABLE_NAME = 'ATTACH'


SELECT ', #{' || SNAKETOCAMEL(COLUMN_NAME) || ',' || 'jdbcType=' ||
    CASE    
        WHEN DATA_TYPE = 'VARCHAR2' THEN 'VARCHAR'
        WHEN DATA_TYPE = 'NUMBER' THEN 'NUMERIC'
        ELSE DATA_TYPE
    END || '}'
FROM COLS
WHERE TABLE_NAME = 'ATTACH';


