--member.memId=회원아이디

SELECT LOWER(TABLE_NAME)||'.'||SNAKETOCAMEL(COLUMN_NAME)||'='|| COMMENTS
FROM USER_COL_COMMENTS
WHERE TABLE_NAME = 'MEMBER';

SELECT LOWER(TABLE_NAME)||'.'||SNAKETOCAMEL(COLUMN_NAME)||'='||COLUMN_NAME
FROM USER_COL_COMMENTS
WHERE TABLE_NAME = 'MEMBER';


이거 입력양식 UI 생성 코드조각이랑 합치면 됨