CREATE TABLE GRADE (
    GR_CODE CHAR(4) NOT NULL
    , GR_NAME VARCHAR2(10 CHAR) NOT NULL
    , CONSTRAINT pk_grade PRIMARY KEY(GR_CODE)
);

COMMENT ON COLUMN GRADE.GR_CODE    IS '학력코드';
COMMENT ON COLUMN GRADE.GR_NAME    IS '학력명';

INSERT INTO GRADE VALUES ('G001', '고졸');
INSERT INTO GRADE VALUES ('G002', '초대졸');
INSERT INTO GRADE VALUES ('G003', '대졸');
INSERT INTO GRADE VALUES ('G004', '대학원졸');
INSERT INTO GRADE VALUES ('G005', '석사');
INSERT INTO GRADE VALUES ('G006', '박사');


CREATE TABLE ALBA (
    AL_ID CHAR(8) NOT NULL
    , AL_NAME VARCHAR2(20) NOT NULL
    , AL_AGE NUMBER(3) NOT NULL
    , AL_ZIP VARCHAR2(7) NOT NULL
    , AL_ADDR1 VARCHAR2(200) NOT NULL
    , AL_ADDR2 VARCHAR2(200) NOT NULL
    , AL_HP VARCHAR2(15) NOT NULL
    , GR_CODE CHAR(4) NOT NULL
    , AL_GEN CHAR(1) NOT NULL
    , AL_MAIL VARCHAR2(100) NOT NULL
    , AL_CAREER VARCHAR2(200)
    , AL_SPEC VARCHAR2(500)
    , AL_DESC VARCHAR2(500)
    , AL_IMG VARCHAR2(300)
    , CONSTRAINT pk_alba PRIMARY KEY(AL_ID)
    , CONSTRAINT fk_alba_grade FOREIGN KEY(GR_CODE) REFERENCES GRADE(GR_CODE)
);

COMMENT ON COLUMN ALBA.AL_ID    IS '알바생코드';
COMMENT ON COLUMN ALBA.AL_NAME   IS '이름';
COMMENT ON COLUMN ALBA.AL_AGE    IS '나이';
COMMENT ON COLUMN ALBA.AL_ZIP    IS '우편번호';
COMMENT ON COLUMN ALBA.AL_ADDR1    IS '주소1';
COMMENT ON COLUMN ALBA.AL_ADDR2   IS '주소2';
COMMENT ON COLUMN ALBA.AL_HP    IS '휴대폰';
COMMENT ON COLUMN ALBA.GR_CODE    IS '학력코드';
COMMENT ON COLUMN ALBA.AL_GEN    IS '성별';
COMMENT ON COLUMN ALBA.AL_MAIL    IS '이메일';
COMMENT ON COLUMN ALBA.AL_CAREER    IS '경력사항';
COMMENT ON COLUMN ALBA.AL_SPEC    IS '특기사항';
COMMENT ON COLUMN ALBA.AL_DESC    IS '비고';
COMMENT ON COLUMN ALBA.AL_IMG    IS '프로필사진경';



CREATE TABLE LICENSE (
    LIC_CODE CHAR(4) NOT NULL
    , LIC_NAME VARCHAR2(50 CHAR) NOT NULL
    , CONSTRAINT pk_license PRIMARY KEY(LIC_CODE)
);

COMMENT ON COLUMN LICENSE.LIC_CODE    IS '자격증코드';
COMMENT ON COLUMN LICENSE.LIC_NAME    IS '자격증명';

INSERT INTO LICENSE VALUES ('L001', '정보처리산업기사');
INSERT INTO LICENSE VALUES ('L002', '정보처리기사');
INSERT INTO LICENSE VALUES ('L003', '정보안산업기사');
INSERT INTO LICENSE VALUES ('L004', '정보보안기사');
INSERT INTO LICENSE VALUES ('L005', 'SQLD');
INSERT INTO LICENSE VALUES ('L006', 'SQLP');

CREATE TABLE LIC_ALBA (
    AL_ID CHAR(8) NOT NULL
    , LIC_CODE CHAR(4) NOT NULL
    , LIC_DATE VARCHAR2(30) NOT NULL
    , LIC_IMG BLOB
    , CONSTRAINT fk_lic_alba_alba FOREIGN KEY(AL_ID) REFERENCES ALBA(AL_ID)
    , CONSTRAINT fk_lic_alba_license FOREIGN KEY(LIC_CODE) REFERENCES LICENSE(LIC_CODE)
)

COMMENT ON COLUMN LIC_ALBA.AL_ID    IS '알바생코드';
COMMENT ON COLUMN LIC_ALBA.LIC_CODE    IS '자격증코드';
COMMENT ON COLUMN LIC_ALBA.LIC_DATE    IS '취득일';
COMMENT ON COLUMN LIC_ALBA.LIC_IMG    IS '자격증사';